name: Sync

on:
  push:
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: version
        name: Check version
        run: bash .github/workflows/tag.sh

    outputs:
      tag: ${{ steps.version.outputs.tag }}

  release:
    needs: [version]
    if: ${{ needs.version.outputs.tag }}

    runs-on: ubuntu-latest

    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install
        run: npm install

      - name: Sync
        run: npm run sync

      - name: Release
        run: >
          curl
          -X POST
          -H "Accept: application/vnd.github.v3+json"
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}"
          https://api.github.com/repos/${{ github.repository }}/releases
          -d '{
            "name": "${{ needs.version.outputs.tag }}",
            "tag_name": "${{ needs.version.outputs.tag }}",
            "target_commitish": "${{ github.sha }}"
          }'
